import prettier from "eslint-plugin-prettier";
import prettierConfig from "eslint-config-prettier";

export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        CustomEvent: "readonly",
        EventTarget: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        Element: "readonly",
        Event: "readonly",
        Node: "readonly",
        // Service Worker globals
        self: "readonly",
        caches: "readonly",
        clients: "readonly",
        skipWaiting: "readonly",
        importScripts: "readonly",
        indexedDB: "readonly",
        IDBRequest: "readonly",
        IDBDatabase: "readonly",
        IDBObjectStore: "readonly",
        IDBTransaction: "readonly",
        IDBIndex: "readonly",
        IDBCursor: "readonly",
        IDBKeyRange: "readonly",
        // Custom Elements API
        customElements: "readonly",
        // Console (for development)
        console: "readonly",
        // Promise
        Promise: "readonly",
        // setTimeout/setInterval
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        // Additional browser APIs
        alert: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Date: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Map: "readonly",
        Set: "readonly",
        Error: "readonly",
        RegExp: "readonly",
        // Node.js globals (for scripts)
        globalThis: "readonly",
      },
    },
    plugins: {
      prettier,
    },
    rules: {
      ...prettierConfig.rules,
      "prettier/prettier": "off",
      "no-console": "off",
      "no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "prefer-const": "warn",
      "no-var": "warn",
      "no-use-before-define": "off",
      eqeqeq: "off",
      "no-eq-null": "off",
      "no-undef": "warn",
      "no-redeclare": "warn",
      "no-unreachable": "warn",
      "no-constant-condition": "warn",
      "no-empty-pattern": "warn",
      "no-func-assign": "warn",
      "no-import-assign": "warn",
      "no-setter-return": "warn",
      "no-sparse-arrays": "warn",
      "no-this-before-super": "warn",
      "no-unsafe-finally": "warn",
      "no-unsafe-negation": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",
    },
  },
  {
    files: ["src/maps/**/*.js", "manage-data.js"],
    languageOptions: {
      globals: {
        google: "readonly",
      },
    },
  },
  {
    files: ["sw*.js", "**/sw*.js"],
    languageOptions: {
      globals: {
        self: "readonly",
        caches: "readonly",
        clients: "readonly",
        skipWaiting: "readonly",
        importScripts: "readonly",
        indexedDB: "readonly",
        IDBRequest: "readonly",
        IDBDatabase: "readonly",
        IDBObjectStore: "readonly",
        IDBTransaction: "readonly",
        IDBIndex: "readonly",
        IDBCursor: "readonly",
        IDBKeyRange: "readonly",
        console: "readonly",
        Promise: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        CacheConfig: "readonly",
      },
    },
  },
  {
    ignores: [
      "node_modules/**",
      "**/node_modules/**",
      "dist/**",
      "build/**",
      "*.min.js",
      "package-lock.json",
      "sw.js",
      "sw-dev.js",
      "sw-core.js",
      "*.md",
      ".eslintignore",
      ".eslintrc*",
      "eslint.config.js",
      ".prettierrc*",
      ".prettierignore",
    ],
  },
];
