export const VALUES = [
  { label: "🏳️‍🌈 LGBTQ+ Friendly", value: "lgbtq_friendly" },
  { label: "👩‍💼 Women-Owned", value: "women_owned" },
  { label: "👥 Minority-Owned", value: "minority_owned" },
  { label: "🧑‍🦯 Disabled-Owned", value: "disabled_owned" },
  { label: "🇺🇸 Veteran-Owned", value: "veteran_owned" },
  { label: "🏢 Small Business", value: "small_business" },
  { label: "🏢 Non-Profit", value: "non_profit" },
  { label: "🏢 Community-Owned", value: "community_owned" },
  { label: "👷 Fair Labor", value: "fair_labor" },
  { label: "🌍 Fair Trade", value: "fair_trade" },
  { label: "🥬 Vegan Friendly", value: "vegan_friendly" },
  { label: "🌍 Direct Trade", value: "direct_trade" },
  { label: "🏢 Locally Owned", value: "locally_owned" },
  { label: "🏢 B Corp", value: "b_corp" },
  { label: "🥬 Vegetarian Friendly", value: "vegetarian_friendly" },
  { label: "🥜 Gluten Free", value: "gluten_free" },
  { label: "🥓 Kosher", value: "kosher" },
  { label: "🍗 Halal", value: "halal" },
  { label: "🌿 Organic", value: "organic" },
];
